[package]
name = "deckview"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.32"
eframe = "0.31.1"
egui = "0.31.1"
env_logger = "0.11.7"
log = "0.4.26"
rusqlite = { version = "0.34.0", features = ["bundled"] }
